### ISSUE TITLE
App crashes when I press "Enable" while my G915 is in the list of Dynamic Lighting devices.

### ISSUE THREAD

**Issue by philkark** [ThioJoe/Dynamic-Lighting-Key-Indicator#2]
When I press "Enable" the App just closes.

The crash report message:

```
Message: An item with the same key has already been added. Key: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
Exception: System.ArgumentException: An item with the same key has already been added. Key: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Dynamic_Lighting_Key_Indicator.MainWindow.FindKeyboardLampArrayDevices() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\Handlers\LightingDeviceHandling.cs:line 72
   at Dynamic_Lighting_Key_Indicator.MainWindow.GetKeyboardLampArrayDeviceSelectorAsync() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\Handlers\LightingDeviceHandling.cs:line 98
   at Dynamic_Lighting_Key_Indicator.MainWindow.StartWatchingForLampArrays() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\MainWindow.xaml.cs:line 268
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
Stack Trace:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Dynamic_Lighting_Key_Indicator.MainWindow.FindKeyboardLampArrayDevices() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\Handlers\LightingDeviceHandling.cs:line 72
   at Dynamic_Lighting_Key_Indicator.MainWindow.GetKeyboardLampArrayDeviceSelectorAsync() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\Handlers\LightingDeviceHandling.cs:line 98
   at Dynamic_Lighting_Key_Indicator.MainWindow.StartWatchingForLampArrays() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\MainWindow.xaml.cs:line 268
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
Source: System.Private.CoreLib
Target Site: Void ThrowAddingDuplicateWithKeyArgumentException[T](T)
```

I changed the key, because I have no idea if that is in any way a security issue for me to post it here :)

**Comment by ThioJoe** [comment]
Hm does it do it if you restart the app? 

I know it has an issue with crashing sometimes if a device is physically connected or disconnected while it's already running, not sure if that was the case here.

**Comment by philkark** [comment]
Hi, thanks for the really fast reply. Yes, I have also rebooted the PC and made sure that the keyboard was listed in the Dynamic Lighting devices list as shown in the picture below BEFORE pressing Enable.

![image](https://github.com/user-attachments/assets/d98ad714-4bb2-460e-9c7a-953814db2187)

**Comment by ThioJoe** [comment]
By any chance is your G915 the wireless version? Or alternatively is your keyboard plugged into a usb hub? 

Edit: Actually that's probably not it. I made a post in the other thread i can link here that might be helpful: https://github.com/ThioJoe/Dynamic-Lighting-Key-Indicator/issues/4#issuecomment-2560267989

**Comment by philkark** [comment]
Hi Thio,
you were right and the device manager setting was even weirder than expected. In the "Keyboards" section my mouse was listed (Razer DeathAdder V3) as a HID Keyboard Device and also had the same "Base container ID" (which was also the one listed as a duplicate in the crash dump) as another device that might have been a copy of the actual G915. After deleting this device, the crash was gone and your App just listed the G915 after pressing Enable. Everything else works just fine. Thank your for the great App. Been waiting for ANY feature to indicate the num lock in any way to me since buying this keyboard.

**Comment by ThioJoe** [comment]
Hm interesting, at least it seems there's a potential workaround for now

**Comment by ThioJoe** [comment]
Going to move the discussion to #4 since there's more people there, but I just posted a new version 1.0.1 which MIGHT fix it. I can't actually test how it works myself though so that's why i'd call it a beta: https://github.com/ThioJoe/Dynamic-Lighting-Key-Indicator/releases/tag/v1.0.1
